language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"

before_install:
  - sudo touch /var/spool/cron/crontabs/$USER
  - sudo chown $USER /var/spool/cron/crontabs/$USER

script:
  - sudo npm test
